[Feature]: Translate install.md to Chinese
open-mmlab/mmselfsup pull request #169
Opened 2022-01-04 12:18 UTC by YuanLiuuuuuu

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Translate install.md to Chinese.

## Modification

Translate install.md to Chinese.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-01-05 09:42 UTC, fangyixiao18 requested changes

2022-01-05 09:42 UTC, fangyixiao18 commented on docs/zh_cn/install.md
> +2. 请参考 [官方教程](https://pytorch.org/) torch 和 torchvision, 例如您可以使用以下命令:
漏了 ‘安装’？

2022-01-11 04:48 UTC, fangyixiao18 approved these changes

2022-01-11 05:58 UTC, Jiahao000 requested changes

2022-01-11 05:58 UTC, Jiahao000 commented on docs/zh_cn/install.md
> +下表显示了与 MMSelfSup 适配的 MMCV, MMDetection 和 MMSegmentation 的版本号. 为避免安装过程中出现问题，请参照下表安装适配的版本。
Please unify the punctuation in sentences and convert them into Chinese. Please also check other parts.

2022-01-11 08:46 UTC, Jiahao000 approved these changes

2022-01-11 08:47 UTC, merged