[Docs] add Chinese version of compatibility.md
open-mmlab/mmselfsup pull request #172
Opened 2022-01-11 09:44 UTC by fangyixiao18

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

## Modification

add  Chinese version of compatibility.md

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-01-13 10:13 UTC, Jiahao000 requested changes

2022-01-13 10:13 UTC, Jiahao000 commented on docs/en/compatibility.md
> +  - As all models' components inherit `BaseModule` from `MMCV`, the models are initialized with `init_cfg`. Please use it to set your initialization. Besides, `init_weights` also can be used.
also can be -> can also be

2022-01-13 10:13 UTC, Jiahao000 commented on docs/zh_cn/compatibility.md
> +  - 由于所有模型的组件继承自 `MMCV` 的 `BaseModule`，模型根据 `init_cfg`进行初始化。请您依照该规范进行初始化设置，`init_weights` 仍然适用。
add space between `init_cfg` and Chinese

2022-01-14 03:41 UTC, Jiahao000 approved these changes

2022-01-14 06:29 UTC, YuanLiuuuuuu requested changes

2022-01-14 06:29 UTC, YuanLiuuuuuu commented on docs/zh_cn/compatibility.md
> +  - 增加 `--cfg-options` 参数来，通过命令行传参对配置文件进行修改。
有点不通顺

2022-01-14 10:09 UTC, YuanLiuuuuuu approved these changes

2022-01-14 10:09 UTC, merged