[Feature] support cpu training
open-mmlab/mmselfsup pull request #188
Opened 2022-01-25 09:51 UTC by fangyixiao18

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Allow users to debug on machines without GPU for convenience
Refer to https://github.com/open-mmlab/mmdetection/pull/7016

## Modification

modify mmselfsup/apis/train.py and tools/train.py

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-01-27 04:50 UTC, YuanLiuuuuuu commented on docs/zh_cn/getting_started.md
> +**注意**: 我们不推荐用户使用 CPU 进行训练， 因为 CPU 的训练速度很慢，而且一些算法使用了 `SyncBN`，该方法需要分布式进行训练，我们支持这个功能是为了方便用户在没有 GPU 的机器上进行调试。
I recommend changing "而且一些算法使用了`SyncBN`" to "一些算法仅支持分布式训练, 例如 `SyncBN`"

2022-01-28 07:15 UTC, YuanLiuuuuuu commented on mmselfsup/apis/train.py
> +        model = MMDataParallel(model, device_ids=cfg.gpu_ids)
Please write UT.

2022-01-28 08:22 UTC, Jiahao000 requested changes
Please write UT.

2022-01-28 08:34 UTC, YuanLiuuuuuu approved these changes

2022-01-28 09:49 UTC, Jiahao000 approved these changes

2022-01-28 09:49 UTC, merged