[Fix] fix bug when loading cifar dataset
open-mmlab/mmselfsup pull request #191
Opened 2022-01-26 12:16 UTC by mitming

## Motivation

Error when running linear evaluation on CIFAR with pre-trained models, cifar images are not loaded.

## Modification

Modify the code of `mmselfsup/datasets/data_sources/cifar.py`, it is no need to load again and the key for cifar image is 'img'.

## Use cases (Optional)

Please refer to this [issue](https://github.com/open-mmlab/mmselfsup/issues/186)

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-01-27 08:18 UTC, fangyixiao18 approved these changes

2022-01-28 08:25 UTC, Jiahao000 requested changes
Could you fix the unit test to pass the check?

2022-01-28 11:57 UTC, Jiahao000 approved these changes

2022-01-28 11:58 UTC, merged

2023-04-07 12:22 UTC, OpenMMLab-Assistant-004 commented
Hi @mitming ！First of all, we want to express our gratitude for your significant PR in the mmselfsup project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG

If you have WeChat，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤