[Fix] Fix config typos for rotation prediction and deepcluster
open-mmlab/mmselfsup pull request #200
Opened 2022-02-02 08:02 UTC by c-liangyu

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Fix config typos for rotation prediction and deepcluster.

## Modification

Fixed config typos for rotation prediction and deepcluster.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [. ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [.] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [. ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [. ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [. ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [. ] CLA has been signed and all committers have signed the CLA in this PR.

2022-02-02 08:14 UTC, Jiahao000 requested changes

2022-02-02 08:14 UTC, Jiahao000 commented on configs/selfsup/deepcluster/deepcluster-sobel_resnet50_8xb64-steplr-200e_in1k.py
> +_base_ = 'deepcluster_resnrt50_8xb64-steplr-200e_in1k.py'
`resnrt` is another typo, can you also fix it?

2022-02-02 08:20 UTC, Jiahao000 approved these changes

2022-02-03 03:28 UTC, fangyixiao18 approved these changes

2022-02-03 10:48 UTC, YuanLiuuuuuu approved these changes

2022-02-03 10:48 UTC, merged

2023-04-04 09:59 UTC, OpenMMLab-Assistant003 commented
Hi @liangyuch！First of all, we want to express our gratitude for your significant PR in the MMSelfSup project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤ @liangyuch

2023-04-07 10:18 UTC, OpenMMLab-Assistant-007 commented
Hi @liangyuch   !
First of all, we want to express our gratitude for your significant PR in the OpenMMLab project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤