[Feature]: barlowtwins
open-mmlab/mmselfsup pull request #207
Opened 2022-02-08 06:11 UTC by xcnick

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-02-09 04:43 UTC, fangyixiao18 reviewed
Thank you for your contribution. Do you have any results or models of barlowtwins based on this PR?

2022-02-09 06:21 UTC, xcnick commented
> Thank you for your contribution. Do you have any results or models of barlowtwins based on this PR?

Sorry, due to lack of computing resources, I only performed the pretraining steps on RTX2080Ti * 2, and observed loss decreasing. Therefore, the config parameters may need to be further adjusted.

I will use 4 * V100 to verify this PR later if possible.

2022-02-09 12:05 UTC, fangyixiao18 commented
> Sorry, due to lack of computing resources, I only performed the pretraining steps on RTX2080Ti * 2, and observed loss decreasing. Therefore, the config parameters may need to be further adjusted.
> 
> I will use 4 * V100 to verify this PR later if possible.

OK, can you checkout a new branch from dev_v0.7.0 and re-create a PR to the dev_v0.7.0 branch? And if you have any updated results,  you can push new commits to the new PR. 
We look forward that your PR can be merged and the BarlowTwins can be released in version 0.7.0 at the begining of the next month.

2022-02-10 06:53 UTC, xcnick commented
> > Sorry, due to lack of computing resources, I only performed the pretraining steps on RTX2080Ti * 2, and observed loss decreasing. Therefore, the config parameters may need to be further adjusted.
> > I will use 4 * V100 to verify this PR later if possible.
> 
> OK, can you checkout a new branch from dev_v0.7.0 and re-create a PR to the dev_v0.7.0 branch? And if you have any updated results, you can push new commits to the new PR. We look forward that your PR can be merged and the BarlowTwins can be released in version 0.7.0 at the begining of the next month.

OK.

2022-03-01 09:12 UTC, xcnick commented
Using the parameters in the code for pretraining in 4*V100, the loss value is about 2000. The top1 acc is 40% when finetune in imagenet1k. So the model did not converge.
Could you help me for the model training?

2022-03-02 08:03 UTC, YuanLiuuuuuu commented
> Using the parameters in the code for pretraining in 4*V100, the loss value is about 2000. The top1 acc is 40% when finetune in imagenet1k. So the model did not converge. Could you help me for the model training?



> Using the parameters in the code for pretraining in 4*V100, the loss value is about 2000. The top1 acc is 40% when finetune in imagenet1k. So the model did not converge. Could you help me for the model training?

If you do not have enough computation resources, you can choose a setting, which has lower computation overhead. Under this setting, you can run the official code and get the log. Finally, you can reproduce the results, according to the log.

2022-03-08 06:51 UTC, YuanLiuuuuuu commented
We have already created a new branch, dev_v0.8.0, for next released version. Please re-submit a PR to merge all your modifications to that branch as soon as possible. Thanks a lot !

2022-03-21 03:47 UTC, YuanLiuuuuuu commented
> Using the parameters in the code for pretraining in 4*V100, the loss value is about 2000. The top1 acc is 40% when finetune in imagenet1k. So the model did not converge. Could you help me for the model training?

Please add the same [decorator](https://github.com/open-mmlab/mmselfsup/pull/207#issuecomment-1061464369) to your algorithm to pass CI.

2022-03-28 06:51 UTC, fangyixiao18 commented
Do you have any updated training results?

2022-03-29 04:01 UTC, xcnick commented
> Do you have any updated training results?

Sorry, the learning rate parameter is adjusted according to the [official code](https://github.com/facebookresearch/barlowtwins/blob/main/main.py), but the loss is around 2000. In contrast, the loss is around 500 in [official log](https://dl.fbaipublicfiles.com/barlowtwins/ljng/stats.txt) when training epoch is 100.

2022-04-01 06:02 UTC, fangyixiao18 commented
> Sorry, the learning rate parameter is adjusted according to the [official code](https://github.com/facebookresearch/barlowtwins/blob/main/main.py), but the loss is around 2000. In contrast, the loss is around 500 in [official log](https://dl.fbaipublicfiles.com/barlowtwins/ljng/stats.txt) when training epoch is 100.

Could you provide your personal contact information? I have sent an e-mail to your gmail account which is displayed on your github homepage.

2022-04-19 08:28 UTC, xcnick commented on configs/selfsup/barlowtwins/barlowtwins_resnet50_8xb32-accum8-coslr-100e_in1k.py
> +
May need to add  `data = dict(samples_per_gpu=32)` to modify the batch_size.

2022-04-24 07:35 UTC, Jiahao000 reviewed
Better to reorganize the algorithms in model zoo in their chronological order. Others LGTM.

2022-04-25 06:47 UTC, YuanLiuuuuuu commented on mmselfsup/models/algorithms/barlowtwins.py
> +                 backbone: object,
type hint should be dict

2022-04-25 06:53 UTC, YuanLiuuuuuu commented on mmselfsup/models/algorithms/barlowtwins.py
> +        self.encoder = nn.Sequential(
This is no need to create an extra ``encoder``, just using ``backbone`` and ``neck`` is OK

2022-04-25 06:56 UTC, YuanLiuuuuuu commented on mmselfsup/models/heads/latent_pred_head.py
>          predictor (dict): Config dict for module of predictor.
```suggestion
        predictor (dict): Config dict for the predictor.
```

2022-04-25 07:09 UTC, YuanLiuuuuuu commented on mmselfsup/models/heads/latent_pred_head.py
> +        in_channels (int): Number of input channels.
missing ``lambd``

2022-04-25 07:09 UTC, YuanLiuuuuuu commented on mmselfsup/models/heads/latent_pred_head.py
> +    def __init__(self, in_channels: int, lambd: float = 0.0051) -> None:
```suggestion
    def __init__(self, in_channels: int, lamb: float = 0.0051) -> None:
```

2022-04-25 07:12 UTC, fangyixiao18 commented on mmselfsup/models/heads/latent_pred_head.py
> +    def __init__(self, in_channels: int, lambd: float = 0.0051) -> None:
Is there any docs to suggest `lamb`?

2022-04-25 12:31 UTC, Jiahao000 requested changes

2022-04-25 12:31 UTC, Jiahao000 commented on docs/en/model_zoo.md
>  ### COCO17 Object Detection and Instance Segmentation
Other benchmark tables in model_zoo should also be reordered.

2022-04-26 09:13 UTC, Jiahao000 approved these changes

2022-04-27 07:46 UTC, YuanLiuuuuuu commented
@fangyixiao18 Please update ``index.rst`` in ``docs``

2022-04-27 10:01 UTC, YuanLiuuuuuu commented on mmselfsup/models/algorithms/barlowtwins.py
> +            img (list[Tensor]): A list of input images with shape
list -> List

2022-04-27 10:02 UTC, YuanLiuuuuuu commented on mmselfsup/models/algorithms/barlowtwins.py
> +            loss[str, Tensor]: A dictionary of loss components
```suggestion
            dict[str, Tensor]: A dictionary of loss components
```

2022-04-27 11:41 UTC, YuanLiuuuuuu approved these changes

2022-04-27 12:26 UTC, merged