Feature/mae official
open-mmlab/mmselfsup pull request #209
Opened 2022-02-09 11:38 UTC by YuanLiuuuuuu

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Add MAE.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-02-15 12:41 UTC, fangyixiao18 requested changes

2022-02-15 12:41 UTC, fangyixiao18 commented on mmselfsup/models/heads/mae_linprobe_head.py
> +class MAELinprobeHead(BaseModule):
merge MAEFinetuneHead and MAELinprobeHead？It can be called MAEClsHead

2022-02-15 12:41 UTC, fangyixiao18 commented on mmselfsup/models/utils/mixup.py
> +class Mixup:
remove mixup

2022-02-23 17:30 UTC, Jiahao000 requested changes

2022-02-23 17:30 UTC, Jiahao000 commented on mmselfsup/models/heads/mae_finetune_head.py
> +# Copyright (c) OpenMMLab. All rights reserved.
Suggest writing `MAEPretrainHead` and `MAEFinetuneHead` into one file named with `mae_head.py`

2022-02-24 03:07 UTC, fangyixiao18 reviewed
fix lint

2022-02-24 03:34 UTC, Jiahao000 requested changes

2022-02-24 03:34 UTC, Jiahao000 commented on mmselfsup/models/heads/mae_pretrain_head.py
> +# Copyright (c) OpenMMLab. All rights reserved.
Change name to `mae_head.py`

2022-02-24 08:44 UTC, fangyixiao18 reviewed
Update en/zh_cn model_zoo

2022-02-24 09:04 UTC, closed without merging