[Docs] translate 0_config.md into Chinese
open-mmlab/mmselfsup pull request #216
Opened 2022-02-21 03:32 UTC by wang11wang

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-02-22 08:48 UTC, fangyixiao18 requested changes

2022-02-22 08:48 UTC, fangyixiao18 commented on docs/zh_cn/tutorials/0_config.md
> +- `simclr_resnet50_mocov2-neck`：在 simclr 中，使用 mocov2-neck 训练，而不是 simclr 自己的 neck
Also remove this line, thanks!

2022-02-22 08:48 UTC, fangyixiao18 commented on docs/zh_cn/tutorials/0_config.md
> +这里我们使用 `'_'` 连接各个部分提升名字可读性。
Remove this line. Actually we forgot to revise this part, now we prefer the format like `{backbone setting}-{neck setting}-{head_setting}`, and the `_` is used like line 30.

2022-02-22 08:48 UTC, fangyixiao18 commented on docs/zh_cn/tutorials/0_config.md
> +这里我们使用 `'_'` 连接各个部分提升名字可读性。
Could you please help us to revise the description in English version tutorial? Thanks!

2022-02-23 06:15 UTC, fangyixiao18 requested changes
Please revise the two minor parts, the other content looks good. Thanks!

2022-02-23 06:15 UTC, fangyixiao18 commented on docs/zh_cn/tutorials/0_config.md
>  {backbone setting}_{neck setting}_{head_setting}
Please change this to `{backbone setting}-{neck setting}-{head_setting}`,  and the corresponding line in English version.

2022-02-23 06:15 UTC, fangyixiao18 commented on docs/zh_cn/tutorials/0_config.md
> +  - `in1k`：数据信息，在 ImageNet1k 数据集上训练
Remove  line 86 - 94, and the corresponding part in English version.

2022-02-23 11:18 UTC, fangyixiao18 approved these changes

2022-02-23 15:20 UTC, Jiahao000 approved these changes

2022-02-24 08:51 UTC, merged

2023-04-04 09:30 UTC, OpenMMLab-gd commented
Hi @wang11wang！First of all, we want to express our gratitude for your significant PR in the MMSelfsup project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤ @wang11wang