[Feature]: MAE official
open-mmlab/mmselfsup pull request #221
Opened 2022-02-24 11:31 UTC by YuanLiuuuuuu

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-02-24 11:37 UTC, fangyixiao18 requested changes

2022-02-24 11:37 UTC, fangyixiao18 commented on docs/en/model_zoo.md
> +| [MAE](https://github.com/open-mmlab/mmselfsup/blob/master/configs/selfsup/mae/README.md)                           | [mae_vit-b-p16_8xb512-coslr-400e_in1k](https://github.com/open-mmlab/mmselfsup/b
`mae_vit-b-p16_8xb512-coslr-400e_in1k` -> `mae_vit-base-p16_8xb512-coslr-400e_in1k`

2022-02-24 11:37 UTC, fangyixiao18 commented on docs/en/model_zoo.md
> +| MAE       | [mae_vit-b-p16_8xb512-coslr-400e_in1k](https://github.com/open-mmlab/mmselfsup/blob/master/configs/selfsup/mocov3/mae_vit-b-p16_8xb512-coslr-400e_in1k.py) |         | 83.1      |
the same name format

2022-02-24 11:37 UTC, fangyixiao18 commented on docs/zh_cn/model_zoo.md
> +| [MAE](https://github.com/open-mmlab/mmselfsup/blob/master/configs/selfsup/mae/README.md)                           | [mae_vit-b-p16_8xb512-coslr-400e_in1k](https://github.com/open-mmlab/mmselfsup/b
the same name format

2022-02-25 03:02 UTC, fangyixiao18 approved these changes

2022-02-25 07:39 UTC, ZwwWayne commented on mmselfsup/core/optimizer/constructor.py
> +        layer_decay (float): base value for layer wise learning rate decay.
It is better to build a new constructor to process this part

2022-02-25 07:40 UTC, ZwwWayne commented on mmselfsup/models/backbones/mae_pretrain_vit.py
> +    A PyTorch implement of : `An Image is Worth 16x16 Words: Transformers
of : -> of:

2022-02-25 08:01 UTC, ZwwWayne commented on mmselfsup/models/heads/mae_head.py
> +        loss = (loss * mask).sum() / mask.sum()
We can use mask to select the pred and target first then calculate the loss to reduce the memory usage?

2022-02-25 09:05 UTC, ZwwWayne commented
imgs_per_gpu -> samples_per_gpu

2022-03-02 09:12 UTC, Jiahao000 approved these changes

2022-03-03 02:45 UTC, merged