[Docs] translate 6_benchmarks.md into Chinese
open-mmlab/mmselfsup pull request #262
Opened 2022-03-29 09:15 UTC by soonera

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Translate 6_benchmarks.md into Chinese.

## Modification

Translate 6_benchmarks.md into Chinese.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-03-30 02:55 UTC, fangyixiao18 requested changes

2022-03-30 02:55 UTC, fangyixiao18 commented on docs/zh_cn/tutorials/6_benchmarks.md
> +# 教程 6：运行基准
Better to change `基准` to `基准评测`, check the whole file

2022-03-30 09:31 UTC, fangyixiao18 approved these changes

2022-03-30 15:24 UTC, Jiahao000 requested changes

2022-03-30 15:24 UTC, Jiahao000 commented on docs/zh_cn/tutorials/6_benchmarks.md
> +关于分类，我们在`tools/benchmarks/classification/`文件夹中提供了脚本，其中有4个 `.sh` 文件和1个文件夹用于 VOC SVM 相关的分类任务。
The translation of `1 folder for ImageNet nearest-neighbor classification task` is missing here.

2022-03-30 15:24 UTC, Jiahao000 commented on docs/zh_cn/tutorials/6_benchmarks.md
> +为了运行这个基准评测，你应该首先准备你的 VOC 数据集，数据预准备的细节请参考[prepare_data.md](https://github.com/open-mmlab/mmselfsup/blob/master/docs/en/prepare_data.md)。
`数据预准备` -> `数据准备`

2022-03-31 04:13 UTC, YuanLiuuuuuu approved these changes

2022-03-31 04:31 UTC, Jiahao000 approved these changes

2022-03-31 04:31 UTC, merged