[Feature] Add resnest backbone.
open-mmlab/mmselfsup pull request #270
Opened 2022-04-04 09:58 UTC by PeterJaq

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Add Resnest backbone support.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

    backbone=dict(
        type='ResNeSt',
        depth=50,
        in_channels=3,
        out_indices=[4],
        norm_cfg=dict(type='BN')

## Checklist

**Before PR**:

- [x] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

2022-04-05 07:32 UTC, fangyixiao18 commented
Thanks for your contirbution!
Please check the code to pass the checks.
Besides, we prefer to use backbone from MMCls and you can import some network bricks from mmcls.

2022-04-05 07:33 UTC, fangyixiao18 requested changes

2022-04-05 07:33 UTC, fangyixiao18 commented on mmselfsup/models/backbones/resnest.py
> +from ..utils import ResLayer
We have removed the ResLayer in MMSelfSup, you can import it from MMCls.

2022-05-01 02:52 UTC, closed without merging

2023-04-12 08:39 UTC, OpenMMLab-Assistant003 commented
Hi @PeterJaq！We are grateful for your efforts in helping improve this open-source project during your personal time. 
Welcome to join OpenMMLab Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA
If you have a WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤ @PeterJaq