Refactor/mae
open-mmlab/mmselfsup pull request #349
Opened 2022-07-16 08:58 UTC by YuanLiuuuuuu

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.
<img width="847" alt="image" src="https://user-images.githubusercontent.com/30762564/179348193-590a3388-4e55-42dc-a4d9-92d2bda6d754.png">

2022-07-18 12:35 UTC, fangyixiao18 requested changes

2022-07-18 12:35 UTC, fangyixiao18 commented on mmselfsup/models/algorithms/mae.py
> +from ..builder import MODELS
better to use `from mmselfsup.registry import MODELS`

2022-07-18 12:35 UTC, fangyixiao18 commented on mmselfsup/models/backbones/mae_vit.py
> +from ..builder import MODELS
The same as above

2022-07-18 12:35 UTC, fangyixiao18 commented on mmselfsup/models/backbones/mae_vit.py
>          super(MAEViT, self).init_weights()
```suggestion
        super().init_weights()
```

2022-07-18 12:35 UTC, fangyixiao18 commented on mmselfsup/models/backbones/mae_vit.py
> +            Tuple[torch.Tensor, Tensor, Tensor]: masked image, mask and the ids
```suggestion
            Tuple[torch.Tensor, torch.Tensor, torch.Tensor]: masked image, mask and the ids
```

2022-07-18 12:35 UTC, fangyixiao18 commented on mmselfsup/models/heads/mae_head.py
> +
Better to add some docstring here, indicate the shape of input tensor and output tensor

2022-07-18 12:35 UTC, fangyixiao18 commented on mmselfsup/models/backbones/mae_vit.py
>          super(MAEViT, self).init_weights()
please check other super init part

2022-07-20 02:48 UTC, fangyixiao18 requested changes

2022-07-20 02:48 UTC, fangyixiao18 commented on configs/selfsup/_base_/datasets/imagenet_mae.py
> +file_client_args = dict(
please change to `disk`

2022-07-20 02:48 UTC, fangyixiao18 commented on configs/selfsup/mae/mae_vit-base-p16_8xb512-coslr-1600e-fp16_in1k.py
> +_base_ = 'mae_vit-base-p16_8xb512-coslr-400e-fp16_in1k.py'
```suggestion
_base_ = 'mae_vit-base-p16_8xb512-fp16-coslr-400e_in1k.py'
```

2022-07-20 09:04 UTC, fangyixiao18 approved these changes

2022-07-20 09:22 UTC, tonysy approved these changes
LGTM

2022-07-20 09:24 UTC, merged