[Tools]: MAE Reconstructed Image Visualization
open-mmlab/mmselfsup pull request #356
Opened 2022-07-19 13:01 UTC by soonera

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Support MAE reconstructed image  visualization

## Modification

(1)  Add init_model() function to Initialize a model from checkpoint.
(2)  Add inference_model() function to infer an image with the loaded model.
(3)  Add forward_test() in Class MAE.
(4)  Add unpatchify() in Class MAEPretrainHead.
(5) Add mae_visualization.py and mae_visualization.ipynb

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-07-22 04:00 UTC, fangyixiao18 requested changes

2022-07-22 04:00 UTC, fangyixiao18 commented on mmselfsup/apis/inference.py
> +        data (PIL): The loaded image.
PIL -> PIL.Image

2022-07-22 04:00 UTC, fangyixiao18 commented on mmselfsup/apis/inference.py
> +        data (Tensor): The loaded image to input model.
```suggestion
        data (torch.Tensor): The loaded image to input model.
```

2022-07-22 04:00 UTC, fangyixiao18 commented on mmselfsup/models/heads/mae_head.py
> +        imgs: (N, 3, H, W)
please follow the format of the docstring
```suggestion
        Args:
            ...
        Returns:
            ...
```

2022-07-22 04:00 UTC, fangyixiao18 commented on mmselfsup/models/heads/mae_head.py
> +        """
check the format of docstring

2022-07-22 04:01 UTC, fangyixiao18 commented
Please also add tutorial for the using of MAE visualization

2022-07-26 02:47 UTC, YuanLiuuuuuu commented on mmselfsup/apis/inference.py
> +        options (dict): Options to override some settings in the used config.
```suggestion
        options (dict, optional): Options to override some settings in the used config.
```

2022-07-26 02:47 UTC, YuanLiuuuuuu commented on mmselfsup/apis/inference.py
> +        config (str or :obj:`mmcv.Config`): Config file path or the config
```suggestion
        config (str or :obj:``mmcv.Config``): Config file path or the config
```

2022-07-26 02:47 UTC, YuanLiuuuuuu commented on mmselfsup/apis/inference.py
> +        checkpoint (str, optional): Checkpoint path. If left as None, the model
Missing docstring for ``device``

2022-07-26 07:09 UTC, YuanLiuuuuuu commented on mmselfsup/apis/inference.py
> +        nn.Module: The constructed model.
```suggestion
        nn.Module: The initialized model.
```

2022-07-26 07:10 UTC, YuanLiuuuuuu commented on mmselfsup/apis/inference.py
> +    # config.model.pretrained = None
This line should be removed

2022-07-26 07:12 UTC, YuanLiuuuuuu commented on mmselfsup/apis/inference.py
> +def inference_model(model, data):
missing typehint

2022-07-26 07:12 UTC, YuanLiuuuuuu commented on mmselfsup/apis/inference.py
> +    """Inference a image with the model.
```suggestion
    """Inference an image with the model.
```

2022-07-26 07:24 UTC, YuanLiuuuuuu reviewed
Please also add the return typehint. In addition, better provide a toy example (initial image, masked image and reconstructed image), showing the visualization results.

2022-07-26 12:20 UTC, closed without merging