[Refactor]: Refactor layer wise lr decay
open-mmlab/mmselfsup pull request #375
Opened 2022-07-25 12:17 UTC by YuanLiuuuuuu

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-07-26 03:10 UTC, fangyixiao18 requested changes

2022-07-26 03:10 UTC, fangyixiao18 commented on mmselfsup/engine/optimizers/layer_decay_optim_wrapper_constructor.py
>                  submodule of DCN, `is_dcn_module` will be passed to
please update the docstring according to the args, `is_dcn_module` is removed

2022-07-26 03:10 UTC, fangyixiao18 commented on mmselfsup/engine/optimizers/layer_decay_optim_wrapper_constructor.py
> +    ``paramwise_cfg`` in the base module will be ignored.
Shall we add warnings if there are some settings in `paramwise_cfg`?

2022-08-01 06:02 UTC, fangyixiao18 approved these changes

2022-08-05 09:35 UTC, tonysy approved these changes
LGTM

2022-08-05 09:35 UTC, tonysy commented on mmselfsup/engine/optimizers/layer_decay_optim_wrapper_constructor.py
> +            ) or name.endswith('.relative_position_bias_table'):
Please add UT for relative_position_bias_table

2022-08-05 09:38 UTC, merged