[Feature]: Add dataset docs
open-mmlab/mmselfsup pull request #437
Opened 2022-08-19 11:44 UTC by YuanLiuuuuuu

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-08-27 07:20 UTC, fangyixiao18 requested changes

2022-08-27 07:20 UTC, fangyixiao18 commented on docs/en/advanced_guides/datasets.md
> +another useful document, [add_datasets](<>).
please add the link, we have the document file

2022-08-27 07:20 UTC, fangyixiao18 commented on docs/en/advanced_guides/datasets.md
> +|              [`RandomGaussianBlu`](TODO)              |
```suggestion
|              [`RandomGaussianBlur`](TODO)              |
```

2022-08-27 07:20 UTC, fangyixiao18 commented on docs/en/advanced_guides/datasets.md
> +you can refer to [transforms](TODO) and [add_transforms](TODO).
the link

2022-08-27 07:20 UTC, fangyixiao18 commented on docs/en/advanced_guides/datasets.md
> +|             [`RotationWithLabels`](TODO)              |
add api path as link

2022-08-30 16:58 UTC, soonera commented on docs/en/advanced_guides/datasets.md
> +`BaseDataset`, we recommend interested readers to refer to the documents in `MMEngine`. `ImageNet`, `ADE20KDataset` and
It's better to put the doc link in MMengine

2022-08-30 16:58 UTC, soonera commented on docs/en/advanced_guides/datasets.md
> +`CocoDataset` are the three commonly used datasets in `MMSelfSup`. Before using them, you should
It seems like an incomplete sentence.

2022-08-30 16:58 UTC, soonera commented on docs/en/advanced_guides/datasets.md
> +Since we do not implement them in `MMSelfSup`, you should `custom import` them in your config:
```suggestion
Since `MMSelfSup` does not implement the datasets from other MM-repos, you should `custom import` them in your config:
```

2022-08-31 03:09 UTC, soonera commented on docs/en/advanced_guides/datasets.md
> +`InfiniteSampler`. In most situation, we can directly use them, instead of implementing customized sampler. But the `DeepClusterSa is a special case, in which we implement the unique index sampling l
DeepClusterSa -> DeepClusterSampler

2022-08-31 03:09 UTC, soonera commented on docs/en/advanced_guides/datasets.md
> +ii) overwrite the `transform` functiond implement your key logic in it. In MMSelfSup, we implement these `transforms` below:
```suggestion
ii) overwrite the `transform()` function and implement your key logic in it. 
In MMSelfSup, we implement these `transforms` below:
```

2022-09-01 08:00 UTC, fangyixiao18 commented on docs/en/advanced_guides/datasets.md
> +`BaseDataset`, we recommend interested readers to refer to the documents in [MMEngine](https://github.com/open-mmlab/mmengine/blob/main/docs/en/tutorials/basedataset.md). `ImageNet`, `ADE20KDataset`
```suggestion
`BaseDataset`, we recommend interested readers to refer to the documents in [MMEngine](https://mmengine.readthedocs.io/en/latest/advanced_tutorials/basedataset.html). `ImageNet`, `ADE20KDataset` and `CocoDataset` are the three commonly used datasets `MMSelfSup`. Before using them, you should refactor your local folder according to
```

2022-09-01 08:00 UTC, fangyixiao18 commented on docs/en/advanced_guides/datasets.md
> +custom_imports=dict(imports='mmcls.datasets', allow_failed_imports=False)
currently we don't need custom_imports

2022-09-02 06:22 UTC, YuanLiuuuuuu commented on docs/en/advanced_guides/datasets.md
> +custom_imports=dict(imports='mmcls.datasets', allow_failed_imports=False)
Will use a separate PR to fix this problem.

2022-09-05 11:17 UTC, fangyixiao18 approved these changes

2022-09-06 12:17 UTC, wangbo-zhao reviewed
we do not implement MultiScaleFlipAug and there are two RandomResizedCrop

2022-09-06 12:17 UTC, wangbo-zhao commented on docs/en/advanced_guides/datasets.md
> +|                           [`PackSelfSupInputs`](mmselfsup.datasets.PackSelfSupInputs)                           |
we do not implement MultiScaleFlipAug and there are two RandomResizedCrop

2022-09-06 12:44 UTC, fangyixiao18 requested changes

2022-09-06 12:44 UTC, fangyixiao18 commented on docs/en/advanced_guides/datasets.md
> +|                          [`RotationWithLabels`](mmselfsup.datasets.RotationWithLabels)                          |
`RandomPatchWithLabels` and `RandomRotation` have not been listed

2022-09-08 09:03 UTC, fangyixiao18 approved these changes

2022-09-08 09:03 UTC, merged