[Feature]: Add structure docs
open-mmlab/mmselfsup pull request #438
Opened 2022-08-19 11:44 UTC by YuanLiuuuuuu

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-08-27 07:28 UTC, fangyixiao18 requested changes

2022-08-27 07:28 UTC, fangyixiao18 commented on docs/en/advanced_guides/structures.md
> +To help uses capture the basic idea of SelfSupDataSample, we give a toy example, about how to create a `SelfSupDataSample`
```suggestion
To help users capture the basic idea of SelfSupDataSample, we give a toy example, about how to create a `SelfSupDataSample`
```

2022-08-27 07:28 UTC, fangyixiao18 commented on docs/en/advanced_guides/structures.md
> +the while tutorial. If you have any problems, you can raise an issue in GitHub, and we will reach you
```suggestion
the whole tutorial. If you have any problems, you can raise an issue in GitHub, and we will reach you
```

2022-08-27 07:28 UTC, fangyixiao18 commented on docs/en/advanced_guides/structures.md
> +If you do not understand data pipeline, you can consult [data transform](https://github.com/open-mmlab/mmcv/blob/transforms/docs/zh_cn/understand_mmcv/data_transform.md). To pack data, implements a d
I think we could use API path here

2022-08-29 09:33 UTC, fangyixiao18 commented on docs/en/advanced_guides/structures.md
> +features in [SelfSupDataSample](mmselfsup/core/data_structures/selfsup_data_sample.py).
please update the api path

2022-08-29 09:35 UTC, tonysy commented on docs/en/advanced_guides/structures.md
> +In MMSelfSup, except for images, `SelfSupDataSample` wraps all information required by models, e.g. mask in MIM and
```suggestion
In MMSelfSup, except for images, `SelfSupDataSample` wraps all information required by models, e.g. `mask` in mask image modeling(MIM) and
```

2022-08-29 09:35 UTC, tonysy commented on docs/en/advanced_guides/structures.md
> +pseudo_label in pretext tasks. In addition to providing information, it can also accept information generated by models,
```suggestion
`pseudo_label` in pretext tasks. In addition to providing information, it can also accept information generated by models,
```

2022-08-29 09:45 UTC, tonysy commented on docs/en/advanced_guides/structures.md
> +If you do not understand data pipeline, you can consult [data transform](https://github.com/open-mmlab/mmcv/blob/transforms/docs/zh_cn/understand_mmcv/data_transform.md). To pack data, we implement a
```suggestion
If you not familiar with data pipeline, you can consult [data transform](https://github.com/open-mmlab/mmcv/blob/transforms/docs/zh_cn/understand_mmcv/data_transform.md). To pack data, we implement a data transform, called [PackSelfSupInputs](mmselfsup.datasets.transforms.PackSelfSupInputs)
```

2022-08-29 09:46 UTC, tonysy reviewed
As inline comments

2022-08-31 02:38 UTC, fangyixiao18 approved these changes

2022-08-31 05:37 UTC, tonysy approved these changes
LGTM

2022-08-31 05:42 UTC, merged