[Doc] dev 1.x/doc add overview
open-mmlab/mmselfsup pull request #446
Opened 2022-08-26 07:50 UTC by tonysy

Add oveview doc

2022-08-29 09:48 UTC, YuanLiuuuuuu commented on docs/en/overview.md
> +Self-supervised learning(SSL) is a promising learning paradigm, which aims to leverage the potential of the huge amount of unlabeled data. In SSL, we typically uses the label generated automatically
```suggestion
Self-supervised learning(SSL) is a promising learning paradigm, which aims to leverage the potential of the huge amount of unlabeled data. In SSL, we typically use the label generated automatically without human labor, to learn a model to extract the discriminative representation of the data. Equipped with the powerful pre-trained model by SSL, we are able to improve various downstream vision tasks currently.
```

2022-08-29 09:49 UTC, YuanLiuuuuuu commented on docs/en/overview.md
> +MMSelfSup follows the modular designed architecture as other OpenMMLab projects. We illustrate the overall framework is illustrated as below:
```suggestion
MMSelfSup follows the modular designed architecture as other OpenMMLab projects. the overall framework is illustrated below:
```

2022-08-29 10:49 UTC, YuanLiuuuuuu commented on docs/en/overview.md
> +  <img src="../../resources/mmselfsup_arch_uml.jpg" width="500"/>
Better use a url, instead of a local link, for keeping the image locally will increase the size of this repo.

2022-08-29 10:50 UTC, YuanLiuuuuuu commented on docs/en/overview.md
> +- For the user who want to try MMSelfSup with various SSL algorithms. We first refer the user to [Get Started](<>) for the **environment setup**.
```suggestion
- For the user who wants to try MMSelfSup with various SSL algorithms. We first refer the user to [Get Started](<>) for the **environment setup**.
```

2022-08-29 10:51 UTC, YuanLiuuuuuu commented on docs/en/overview.md
> +- Also, we provide some analysis tools and visualization tools[(Useful Tools)](https://mmselfsup.readthedocs.io/en/dev-1.x/user_guides/#downstream-tasks) to help  diagnosing the algorithm.
```suggestion
- Also, we provide some analysis tools and visualization tools[(Useful Tools)](https://mmselfsup.readthedocs.io/en/dev-1.x/user_guides/#downstream-tasks) to help  diagnose the algorithm.
```

2022-08-29 10:53 UTC, YuanLiuuuuuu commented on docs/en/overview.md
> +If you are new to SSL, we recommend using the [Model Zoo](https://mmselfsup.readthedocs.io/en/dev-1.x/model_zoo.html) as a reference to learn the milestones SSL algorithms.
```suggestion
If you are new to SSL, we recommend using the [Model Zoo](https://mmselfsup.readthedocs.io/en/dev-1.x/model_zoo.html) as a reference to learn the representative SSL algorithms.
```

2022-08-29 12:11 UTC, fangyixiao18 requested changes

2022-08-29 12:11 UTC, fangyixiao18 commented on docs/en/overview.md
> +- For the user who want to try MMSelfSup with various SSL algorithms. We first refer the user to [Get Started](<>) for the **environment setup**.
```suggestion
- For the user who want to try MMSelfSup with various SSL algorithms. We first refer the user to [Get Started](./get_started.md) for the **environment setup**.
```

2022-08-29 12:11 UTC, fangyixiao18 commented on docs/en/overview.md
> +  <img src="../../resources/mmselfsup_arch_uml.jpg" width="500"/>
The arch jpg is outdated, here is the updated arch. And the link could be updated with the url below
![mmselfsup_arch](https://user-images.githubusercontent.com/36138628/187197848-e518052f-b75e-4981-bed7-d71dc1a5a0fb.jpg)

2022-08-29 13:02 UTC, fangyixiao18 commented on docs/en/overview.md
> +- Also, we provide some analysis tools and visualization tools[(Useful Tools)](https://mmselfsup.readthedocs.io/en/dev-1.x/user_guides/#downstream-tasks) to help  diagnose the algorithm.
```suggestion
- Also, we provide some analysis tools and visualization tools [Useful Tools](https://mmselfsup.readthedocs.io/en/dev-1.x/user_guides/#downstream-tasks) to help  diagnose the algorithm.
```

2022-08-29 13:03 UTC, fangyixiao18 commented
besides, the `mmselfsup_arch_uml.jpg` can be deleted.

2022-08-30 09:12 UTC, fangyixiao18 approved these changes

2022-08-30 09:26 UTC, YuanLiuuuuuu approved these changes

2022-08-30 09:27 UTC, merged