[Docs]: Add advanced_guides/engine.md
open-mmlab/mmselfsup pull request #454
Opened 2022-08-29 09:06 UTC by soonera

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Add advanced_guides/engine.md

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-08-29 09:08 UTC, tonysy commented on docs/en/advanced_guides/engine.md
> +### default hooks
```suggestion
### Default hooks
```

2022-08-29 09:18 UTC, tonysy commented on docs/en/advanced_guides/engine.md
> +Some common hooks are not registered through `custom_hooks`, they are
```suggestion
The following common hooks are already reigistered by [default][(https://github.com/open-mmlab/mmselfsup/blob/dev-1.x/configs/selfsup/_base_/default_runtime.py#L3), which is implemented through [`register_default_hooks`](https://github.com/open-mmlab/mmengine/blob/main/mmengine/runner/runner.py#L1750) in MMEngine
```

2022-08-29 09:19 UTC, tonysy commented on docs/en/advanced_guides/engine.md
> +### Use other implemented hooks
```suggestion
### Other hooks implemented in MMEngine
```

2022-08-29 09:20 UTC, tonysy commented on docs/en/advanced_guides/engine.md
> +### Implemented hooks in MMSelfsup
```suggestion
### Hooks implemented in MMSelfsup
```

2022-08-29 09:22 UTC, tonysy commented on docs/en/advanced_guides/engine.md
> +#### Customize optimizer supported by Pytorch
```suggestion
#### Customize optimizer supported by PyTorch
```

2022-08-29 09:23 UTC, tonysy commented on docs/en/advanced_guides/engine.md
> +### Optimizer Wrapper
```suggestion
### Optimizer wrapper
```

2022-08-29 09:23 UTC, tonysy commented on docs/en/advanced_guides/engine.md
> +#### automatic mixed precision training
```suggestion
#### Automatic mixed precision(AMP) training
```

2022-08-29 09:24 UTC, tonysy commented on docs/en/advanced_guides/engine.md
> +#### Implemented constructors in MMSelfsup
```suggestion
#### Constructors implemented in MMSelfsup
```

2022-08-29 09:25 UTC, tonysy reviewed
As inline comments

2022-08-29 12:24 UTC, fangyixiao18 commented on docs/en/advanced_guides/engine.md
> +- [DeepClusterHook](https://github.com/open-mmlab/mmselfsup/blob/dev-1.x/mmselfsup/engine/hooks/deepcluster_hook.py)
Better to use API path instead of github link, the same comments about below

2022-09-01 08:17 UTC, fangyixiao18 requested changes

2022-09-01 08:17 UTC, fangyixiao18 commented on docs/en/advanced_guides/engine.md
> +
Add one description here to we introduce `Optimizer` section through 3 different parts

2022-09-01 08:17 UTC, fangyixiao18 commented on docs/en/advanced_guides/engine.md
> +We already support to use all the optimizers implemented by PyTorch, see `mmengine/optim/optimizer/builder.py`. To use and modify them, please change the `optimizer` field of config files.
```suggestion
We have already supported all the optimizers implemented by PyTorch, see `mmengine/optim/optimizer/builder.py`. To use and modify them, please change the `optimizer` field of config files.
```

2022-09-01 08:17 UTC, fangyixiao18 commented on docs/en/advanced_guides/engine.md
> +Some models may have some parameter-specific settings for optimization, for example, no weight decay to the BatchNorm layer and the bias in each layer. To finely configure them, we can use the `param
```suggestion
Some models may have some parameter-specific settings for optimization, for example, no weight decay to the BatchNorm layer and the bias in each layer. To finely configure them, we can use the `paramwise_cfg` in optimizer.
```

2022-09-01 08:17 UTC, fangyixiao18 commented on docs/en/advanced_guides/engine.md
> +For example, if we do not want to apply weight decay to the parameters of `BatchNorm` or `GroupNorm`, and the bias in each layer, we can use following config file:
Take MAE config as an example and correct the code snippet

2022-09-01 08:17 UTC, fangyixiao18 commented on docs/en/advanced_guides/engine.md
> +- [LARS](https://github.com/open-mmlab/mmselfsup/blob/dev-1.x/mmselfsup/engine/optimizers/lars.py)
```suggestion
- [LARS](mmselfsup.engine.optimizers.LARS)
```

2022-09-01 08:17 UTC, fangyixiao18 commented on docs/en/advanced_guides/engine.md
> +- [LearningRateDecayOptimWrapperConstructor](https://github.com/open-mmlab/mmselfsup/blob/dev-1.x/mmselfsup/engine/optimizers/layer_decay_optim_wrapper_constructor.py#L64)
```suggestion
- [LearningRateDecayOptimWrapperConstructor](mmselfsup.engine.optimizers.LearningRateDecayOptimWrapperConstructor)
```

2022-09-05 11:19 UTC, fangyixiao18 approved these changes

2022-09-07 06:11 UTC, merged