[Docs]: Add advanced_guides/evaluation.md
open-mmlab/mmselfsup pull request #456
Opened 2022-08-29 16:36 UTC by soonera

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Add advanced_guides/evaluation.md

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-08-30 06:43 UTC, YuanLiuuuuuu commented on docs/en/advanced_guides/evaluation.md
> +![img](https://user-images.githubusercontent.com/15977946/163718224-20a4970a-e540-4a3a-8b01-bf0a604c6841.jpg)
I am a little bit confused by the diagram. Could you please give more detailed explanation?

2022-08-30 06:46 UTC, YuanLiuuuuuu commented on docs/en/advanced_guides/evaluation.md
> +During benchmark, evaluation is used on downstream tasks with other OpenMMLab projects like `MMDetection` and `MMSegmentation` .
```suggestion
During benchmark, the pre-trained model will use some other OpenMMLab repos, e.g. MMClassification and MMSegmentation, which have already implemented their own evaluation funtionalities. 
```

2022-08-30 06:47 UTC, YuanLiuuuuuu commented on docs/en/advanced_guides/evaluation.md
> +Some evaluation functions are impleted in MMSelfSup, as follows:
```suggestion
But MMSelfSup also implements some custom evaluation functionalities, shown as below,
```

2022-09-01 08:30 UTC, fangyixiao18 requested changes

2022-09-01 08:30 UTC, fangyixiao18 commented on docs/en/advanced_guides/evaluation.md
> +During benchmark, the pre-trained model will use some other OpenMMLab repos, e.g. MMClassification and MMSegmentation, which have already implemented their own evaluation functionalities.
```suggestion
During benchmark, the pre-trained models need other downstream tasks to evaluate the performance, e.g. classification, detection, segmentation, etc. It is recommended to run downstream tasks with other OpenMMLab repos, such as MMClassification or MMDetection, which have already implemented their own evaluation functionalities.
```

2022-09-01 08:30 UTC, fangyixiao18 commented on docs/en/advanced_guides/evaluation.md
> +But MMSelfSup also implements some custom evaluation functionalities, shown as below:
```suggestion
But MMSelfSup also implements some custom evaluation functionalities to support downstream tasks, shown as below:
```

2022-09-01 08:30 UTC, fangyixiao18 commented on docs/en/advanced_guides/evaluation.md
> +- [`knn_classifier()`](https://github.com/open-mmlab/mmselfsup/blob/dev-1.x/mmselfsup/evaluation/functional/knn_classifier.py)
```suggestion
- [`knn_classifier()`](mmselfsup.evaluation.functional.knn_classifier)
```

2022-09-01 08:30 UTC, fangyixiao18 commented on docs/en/advanced_guides/evaluation.md
> +- [`ResLayerExtraNorm`](https://github.com/open-mmlab/mmselfsup/blob/dev-1.x/mmselfsup/evaluation/functional/res_layer_extra_norm.py)
```suggestion
- [`ResLayerExtraNorm`](mmselfsup.evaluation.functional.ResLayerExtraNorm)
```

2022-09-01 08:30 UTC, fangyixiao18 commented on docs/en/advanced_guides/evaluation.md
> +During model validation and testing, quantitative evaluation is often required. `Metric` and `Evaluator` have been implemented in MMEngine to perform this function. See [MMEngine Doc](https://github.
```suggestion
During model validation and testing, quantitative evaluation is often required. `Metric` and `Evaluator` have been implemented in MMEngine to perform this function. See [MMEngine Doc](https://mmengine.readthedocs.io/en/latest/design/evaluation.html).
```

2022-09-01 08:30 UTC, fangyixiao18 commented on docs/en/advanced_guides/evaluation.md
> +Custom `Metric` and `Evaluator`  are also supported, see [MMEngine Doc](https://github.com/open-mmlab/mmengine/blob/main/docs/zh_cn/tutorials/evaluation.md)
```suggestion
Custom `Metric` and `Evaluator`  are also supported, see [MMEngine Doc](https://mmengine.readthedocs.io/en/latest/design/evaluation.html)
```

2022-09-05 11:21 UTC, fangyixiao18 approved these changes

2022-09-07 06:12 UTC, merged