[Doc] Add custom dataset tutorial
open-mmlab/mmselfsup pull request #522
Opened 2022-10-18 07:31 UTC by tonysy

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2022-10-18 08:53 UTC, fangyixiao18 requested changes

2022-10-18 08:53 UTC, fangyixiao18 commented on docs/en/user_guides/4_pretrain_custom_dataset.md
> +It should be like `/dataset/my_custom_dataset`
Better to keep consistent with config (`'data/custom_dataset/'`)

2022-10-18 08:53 UTC, fangyixiao18 commented on docs/en/user_guides/4_pretrain_custom_dataset.md
> +- Set the `dataset_type = 'mmcls.CustomDataset'`, and the path of the custom dataset ` dataset_type = /dataset/my_custom_dataset`.
```suggestion
- Set the `dataset_type = 'mmcls.CustomDataset'`, and the path of the custom dataset ` data_root = data/custom_dataset/`.
```

2022-10-18 08:53 UTC, fangyixiao18 commented on docs/en/user_guides/4_pretrain_custom_dataset.md
> +
Better to remind users to install MMDet and check the version at the beginning

2022-10-18 08:55 UTC, fangyixiao18 requested changes

2022-10-18 08:55 UTC, fangyixiao18 commented on docs/en/user_guides/4_pretrain_custom_dataset.md
> +bash tools/dist_train.sh ${CONFIG} ${GPUS} --cfg-options ${PRETRAIN}
--cfg-options model.pretrained=......

2022-10-18 09:15 UTC, YuanLiuuuuuu commented on docs/en/user_guides/4_pretrain_custom_dataset.md
> +In MMSelfSup, We support the `CustomDataset` from MMClassification,  which is able to read the images within the specified folder directly. You only need to prepare the path information of the custom
Maybe we can add something like: similar to the ``ImageFolder`` in ``torchvision``.

2022-10-18 09:17 UTC, YuanLiuuuuuu commented on docs/en/user_guides/4_pretrain_custom_dataset.md
> +Here, we would like to use `configs/selfsup/mae/mae_vit-base-p16_8xb512-coslr-400e_in1k.py` as the example. We first copy this config file and rename it as `mae_vit-base-p16_8xb512-coslr-400e_custom_
According to naming rules for config files, `mae_vit-base-p16_8xb512-coslr-400e_custom_dataset.py` should be renamed to `mae_vit-base-p16_8xb512-coslr-400e-${custom_dataset}.py`.

2022-10-18 09:25 UTC, YuanLiuuuuuu commented on docs/en/user_guides/4_pretrain_custom_dataset.md
> +- Set the `dataset_type = 'mmcls.CustomDataset'`, and the path of the custom dataset ` dataset_type = /dataset/my_custom_dataset`.
Better to remind the user to add the ``custom_dataset`` in ``mmcls``, instead of ``mmselfsup``.

2022-10-18 09:25 UTC, YuanLiuuuuuu commented on docs/en/user_guides/4_pretrain_custom_dataset.md
> +And edited the config will be like this:
```suggestion
And the edited config will be like this:
```

2022-10-18 09:31 UTC, YuanLiuuuuuu commented on docs/en/user_guides/4_pretrain_custom_dataset.md
> +We provide an example of using SimCLR on custom dataset, the main idea is similar with the [Train MAE on Custom Dataset
```suggestion
We provide an example of using SimCLR on custom dataset, the main idea is similar to the [Train MAE on Custom Dataset
```

2022-10-19 02:39 UTC, YuanLiuuuuuu approved these changes

2022-10-19 03:07 UTC, fangyixiao18 approved these changes

2022-10-19 03:07 UTC, merged