Dev1.x translate
open-mmlab/mmselfsup pull request #651
Opened 2023-01-03 01:21 UTC by JetstramSam

翻译了models.md 和 structures.md 和 transforms.md

2023-01-03 06:37 UTC, fangyixiao18 commented on docs/en/advanced_guides/models.md
> +-算法，包括模型的全部模块和构造算法时需要用到的子模块。
```suggestion
- 算法，包括模型的全部模块和构造算法时需要用到的子模块。
```

2023-01-03 06:37 UTC, fangyixiao18 commented on docs/en/advanced_guides/models.md
> +'forward'函数是结果的入口。然而，它和大多数Pytorch代码中只有一种模式的'forward'函数不同。在'forward'函数中你会逻辑混乱，这会限制粗糙度。正如下面代码所示，MMSelfSup中的'forward'函数有三种模式：张量，损失和预测。
```suggestion
`forward` 函数是结果的入口。然而，它和大多数 Pytorch 代码中只有一种模式的 `forward` 函数不同。在 `forward` 函数中你会逻辑混乱，这会限制粗糙度。正如下面代码所示，MMSelfSup 中的 `forward` 函数有三种模式：张量，损失和预测。
```

2023-01-03 07:01 UTC, fangyixiao18 requested changes

2023-01-03 07:01 UTC, fangyixiao18 commented on docs/en/advanced_guides/structures.md
> +`SelfSupDataSample`继承[MMEngine](https://github.com/open-mmlab/mmengine)中使用的`BaseDataElement`。如果需要深入了解`BaseDataElement`，我们建议参考[BaseDataElement](https://github.com/open-mmlab/mmengine/blob/main/docs/zh
```suggestion
`SelfSupDataSample`继承[MMEngine](https://github.com/open-mmlab/mmengine)中使用的`BaseDataElement`。如果需要深入了解`BaseDataElement`，我们建议参考[BaseDataElement](https://github.com/open-mmlab/mmengine/blob/main/docs/zh_cn/advanced_tutorials/data_element.md)。在这些教程中，我们主要讨论[SelfSupDataSample](mmselfsup.structures.SelfSupDataSample)中一些定制化的属性。
```

2023-01-03 07:01 UTC, fangyixiao18 commented on docs/en/advanced_guides/structures.md
> +-gt_label（标签数据），包含图片的真实标签。
please check Chinese name of LabelData, InstanceData, BaseDataElement in MMEngine
https://github.com/open-mmlab/mmengine/blob/main/docs/zh_cn/advanced_tutorials/data_element.md

2023-01-03 07:01 UTC, fangyixiao18 commented on docs/en/advanced_guides/transforms.md
> +## 转换概述
用 数据变换 这个翻译吧，比 转换 更加容易理解

2023-01-03 07:01 UTC, fangyixiao18 commented on docs/en/advanced_guides/transforms.md
> +2.不同视角看同一照片的转换打包器。这个在[wrappers.py](https://github.com/open-mmlab/mmselfsup/blob/1.x/mmselfsup/datasets/transforms/wrappers.py)中定义过。
```suggestion
2. 不同视角看同一照片的转换打包器，这个定义在 [wrappers.py](https://github.com/open-mmlab/mmselfsup/blob/1.x/mmselfsup/datasets/transforms/wrappers.py)。
```

2023-01-03 07:01 UTC, fangyixiao18 commented on docs/en/advanced_guides/transforms.md
> +## MultiView概论
```suggestion
## MultiView 简介
```

2023-01-03 07:01 UTC, fangyixiao18 commented on docs/en/advanced_guides/transforms.md
> +我们建一个名为[`PackSelfSupInputs`](mmselfsup.datasets.transforms.PackSelfSupInputs)的类来将数据转换为能输入算法中的格式。这种转换通常在通信流水线的后面，就像这样：
```suggestion
我们建一个名为[`PackSelfSupInputs`](mmselfsup.datasets.transforms.PackSelfSupInputs)的类来将数据转换为能输入算法中的格式。这种转换通常在数据管道的最后，就像这样：
```
pipeline 的话，翻成 数据管道吧，全文可以检查一下

2023-01-03 08:30 UTC, JetstramSam commented on docs/en/advanced_guides/transforms.md
> +我们建一个名为[`PackSelfSupInputs`](mmselfsup.datasets.transforms.PackSelfSupInputs)的类来将数据转换为能输入算法中的格式。这种转换通常在通信流水线的后面，就像这样：
改好了，那两个好像还是报错。commit次数有些多，需要的话我再开个分支重新PR。

2023-01-03 09:02 UTC, fangyixiao18 commented on docs/en/advanced_guides/transforms.md
> +我们建一个名为[`PackSelfSupInputs`](mmselfsup.datasets.transforms.PackSelfSupInputs)的类来将数据转换为能输入算法中的格式。这种转换通常在通信流水线的后面，就像这样：
> 改好了，那两个好像还是报错。commit次数有些多，需要的话我再开个分支重新PR。

没事，commit次数没关系

2023-01-03 09:34 UTC, fangyixiao18 requested changes

2023-01-03 09:34 UTC, fangyixiao18 commented on docs/en/advanced_guides/models.md
> +MMSelfSup 提供一个基础模型,名为 `BaseModel` , 所以的算法都应该继承这个基础模型。而且所有子模块（除了记忆部分）在算法初始化时都基于这个基础模型。记忆部分在每个算法的 `__init__` 中被构造。损失部分在构造头部部分时被构造。
```suggestion
MMSelfSup 提供一个基础模型，名为 `BaseModel`，所以的算法都应该继承这个基础模型，而且所有子模块（除了记忆部分）在基础模型中进行初始化。记忆部分在对应算法的 `__init__` 中被构造。损失部分在头部部分初始化时被构造。
```

2023-01-03 09:34 UTC, fangyixiao18 commented on docs/en/advanced_guides/models.md
> +- 损失，如果模式为 `loss`，`forward` 函数就返回预测值与目标之间的损失。同样的，您应该重写其中的 `extract_feat` 部分才能让定制化的提取过程有效。
```suggestion
- 损失，如果模式为 `loss`，`forward` 函数就返回预测值与目标之间的损失。同样的，您应该重写其中的 `loss` 部分才能让定制化的提取过程有效。
```

2023-01-03 09:34 UTC, fangyixiao18 commented on docs/en/advanced_guides/models.md
> +`forward` 函数是结果的入口。然而，它和大多数 Pytorch 代码中只有一种模式的 `forward` 函数不同。在 `forward` 函数中您会逻辑混乱，这会限制粗糙度。正如下面代码所示，MMSelfSup 中的 `forward` 函数有三种模式：张量，损失和预测。
```suggestion
`forward` 函数是结果的入口。然而，它和大多数 Pytorch 代码中只有一种模式的 `forward` 函数不同。MMSelfSup 把所有的逻辑都混杂在 `forward` 中，从而限制了该方法的可拓展性。正如下面代码所示，MMSelfSup 中的 `forward` 函数根据不同模式进行前向处理，目前共有三种模式：张量，损失和预测。
```

2023-01-03 09:34 UTC, fangyixiao18 commented on docs/en/advanced_guides/structures.md
> +# 结构
数据结构

2023-01-03 09:34 UTC, fangyixiao18 commented on docs/en/advanced_guides/transforms.md
> +我们为一些算法建名为 [`MultiView`](mmselfsup.datasets.transforms.MultiView) 的多角度照片输入的包装器，比如 MOCO, SimCLR和 SwAV。在配置文件中，我们能这样定义：
```suggestion
我们为一些算法定义了名为 [`MultiView`](mmselfsup.datasets.transforms.MultiView) 的多角度照片输入的包装器，比如 MoCo 系列，SimCLR，SwAV 等。在配置文件中，我们能这样定义：
```

2023-01-04 03:24 UTC, fangyixiao18 approved these changes

2023-01-04 03:26 UTC, merged