Add engine.md and evaluation.md in zh_cn
open-mmlab/mmselfsup pull request #725
Opened 2023-03-26 07:01 UTC by xuan07472

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Translate engine.md and evaluation.md in docs/en

## Modification

Add engine.md and evaluation.md in docs/zh_cn

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects, like MMDet or MMSeg.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2023-03-27 07:35 UTC, fangyixiao18 requested changes

2023-03-27 07:35 UTC, fangyixiao18 commented on docs/zh_cn/advanced_guides/engine.md
> +例如使用  `EMAHook`, start_iters 是 500:
```suggestion
例如使用  `DenseCLHook`, start_iters 是 500:
```

2023-03-27 07:35 UTC, fangyixiao18 commented on docs/zh_cn/advanced_guides/engine.md
> +`AmpOptimWrapper` 中 `loss_scale` 的默认设置是 is `dynamic`.
```suggestion
`AmpOptimWrapper` 中 `loss_scale` 的默认设置是 `dynamic`.
```

2023-03-27 07:35 UTC, fangyixiao18 commented on docs/zh_cn/advanced_guides/engine.md
> +`LearningRateDecayOptimWrapperConstructor` 为主干网络的不同层设置不同的学习率. 注意: 目前,这个优化器构造器是为ViT 和 Swin 构建的.
```suggestion
`LearningRateDecayOptimWrapperConstructor` 为主干网络的不同层设置不同的学习率. 注意: 目前,这个优化器构造器是为 ViT, Swin, MixMIM 构建的.
```

2023-03-27 07:35 UTC, fangyixiao18 commented on docs/zh_cn/advanced_guides/engine.md
> +注意: `paramwise_cfg` 将被忽略, 可以写成  `paramwise_cfg=dict()` .  默认情况下, `LearningRateDecayOptimWrapperConstructor` 不会自动对 `normalization parameters`, `bias`, `position embedding`, `class token` 和 `relative p
```suggestion
注意: `paramwise_cfg` 只支持 `weight_decay` 的自定义。
```
please also update en version, thx

2023-03-27 12:28 UTC, xuan07472 reviewed
I accidentally merged the 1.x branch, but found it just has this extra PR: [open-mmlab#723](https://github.com/open-mmlab/mmselfsup/pull/723), do I need to fall back to the previous version?

2023-03-28 03:08 UTC, fangyixiao18 commented
> I accidentally merged the 1.x branch, but found it just has this extra PR: [open-mmlab#723](https://github.com/open-mmlab/mmselfsup/pull/723), do I need to fall back to the previous version?

yes, please fall back to your previous version

2023-03-28 04:37 UTC, xuan07472 commented
> > I accidentally merged the 1.x branch, but found it just has this extra PR: [open-mmlab#723](https://github.com/open-mmlab/mmselfsup/pull/723), do I need to fall back to the previous version?
> 
> yes, please fall back to your previous version

Ok, I have returned the version and resubmitted the revision. Please check it.

2023-03-28 10:07 UTC, fangyixiao18 requested changes

2023-03-28 10:07 UTC, fangyixiao18 commented on docs/en/advanced_guides/engine.md
> +Note: `paramwise_cfg` only supports the customization of `weight _ decline`.
```suggestion
Note: `paramwise_cfg` only supports the customization of `weight_decay` in `LearningRateDecayOptimWrapperConstructor`.
```

2023-03-28 10:07 UTC, fangyixiao18 commented on docs/zh_cn/advanced_guides/engine.md
> +注意: `paramwise_cfg` 只支持 `weight_decay` 的自定义.
```suggestion
注意: 在 `LearningRateDecayOptimWrapperConstructor` 中，`paramwise_cfg` 只支持 `weight_decay` 的自定义.
```

2023-03-28 11:30 UTC, fangyixiao18 approved these changes

2023-03-28 11:31 UTC, merged