Translate customize_runtime.md
open-mmlab/mmselfsup pull request #734
Opened 2023-03-31 13:15 UTC by jts250

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Translating the Chinese document customize_runtime.md.

## Modification

Translating the Chinese document customize_runtime.md.

2023-04-03 07:28 UTC, fangyixiao18 requested changes

2023-04-03 07:28 UTC, fangyixiao18 commented on docs/zh_cn/advanced_guides/customize_runtime.md
> +  - [调度器(Scheduler)](<#调度器(Scheduler)>)
please check the correctness of the TOC

2023-04-03 07:28 UTC, fangyixiao18 commented on docs/zh_cn/advanced_guides/customize_runtime.md
> +以下是MAE的 `optim_wrapper` 示例。以下配置将 `pos_embed`, `mask_token`, `cls_token` 模块和名称包含`ln`和`bias`的那些层的权重衰减乘法设置为0。在训练过程中，这些模块的权重衰减将是 `weight_decay * decay_mult`。
```suggestion
以下是MAE的 `optim_wrapper` 示例。以下配置将 `pos_embed`, `mask_token`, `cls_token` 模块和名称包含`ln`和`bias`的那些层的权重衰减的乘法乘数设置为 0。在训练过程中，这些模块的权重衰减将是 `weight_decay * decay_mult`。
```

2023-04-03 12:47 UTC, jts250 commented on docs/zh_cn/advanced_guides/customize_runtime.md
> +  - [调度器(Scheduler)](<#调度器(Scheduler)>)
Thank you for pointing out this error. I have fixed it in the new version of the document.

2023-04-04 02:43 UTC, fangyixiao18 approved these changes

2023-04-04 02:46 UTC, merged